dicom_web_viewer/dicom_web_viewer/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from misl_viewer import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dicom_web_viewer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^viewer/', include('misl_viewer.urls',namespace='misl_viewer')),
)

dicom_web_viewer/misl_viewer/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from misl_viewer import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),   # home
    url(r'^upload/$', views.Upload, name='upload'),  # 保存
    url(r'^list/$', views.list, name='list'),  #一覧
    url(r'^test/$', views.test, name='test'),  #テスト
    url(r'^display/(?P<image_id>\d+)/$', views.display, name='display'),  #選択画像表示
    url(r'^add/$', views.MultiFileUpload, name='add'),  #登録
    url(r'^del/(?P<image_id>\d+)/$', views.Image_del, name='image_del'),  #登録
#    url(r'^book/mod/(?P<book_id>\d+)/$', views.book_edit, name='book_mod'),  # 修正
#    url(r'^book/del/(?P<book_id>\d+)/$', views.book_del, name='book_del'),   # 削除

)

dicom_web_viewer/misl_viewer/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.utils.timezone import now

class Image(models.Model):
    upload_date = models.DateTimeField(default=now)
    file_name = models.CharField(max_length = 255)
    set_proc = models.CharField(max_length=255,blank=True, default='DEFAULT_PROC')
    set_tag = models.CharField(max_length=255,blank=True,default='DEFAULT_TAG')
    set_threshold = models.CharField(max_length=255,blank=True,default='DEFAULT_THRESHOLD')
#    upload_date = models.DateTimeField('date upload')
    def __unicode__(self):
        return self.file_name

dicom_web_viewer/misl_viewer/forms.py
# -*- coding: utf-8 -*-
from django import forms

CHOICES = (
        (0, '脳部位の体積算出'),
        (1, '画像処理'),
        (2, '処理をしない'),
        )
CHOICES_tag = (
        (0,'海馬の体積：Hippocampus'),
        (2,'帯状回の体積：Cingulum'),
        (3,'扁桃体の体積：Amygdala'),
        (4,'前頭葉の体積：Frontal_Lobe'),
        )

class ExampleForm(forms.Form):
    select_processing = forms.ChoiceField(choices=CHOICES, label='処理の選択',initial='実行したい処理を選択して下さい')
    choice_tag = forms.MultipleChoiceField(label='追加するタグ',choices=CHOICES_tag, widget=forms.CheckboxSelectMultiple)
    set_threshold0 = forms.IntegerField(label='海馬の体積の閾値の設定（単位：mm^3）',initial=3650)
    set_threshold2 = forms.IntegerField(label='帯状回の閾値の設定（単位：mm^3）',initial=5500)
    set_threshold3 = forms.IntegerField(label='扁桃体の閾値の設定（単位：mm^3）',initial=1248)
    set_threshold4 = forms.IntegerField(label='前頭葉の閾値の設定（単位：cm^3）',initial=550)
#    radio_choice = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)
#    multiple_choice = forms.MultipleChoiceField(choices=CHOICES)
#    multiple_checkbox = forms.MultipleChoiceField(choices=CHOICES, widget=forms.CheckboxSelectMultiple)
#    file_fied = forms.FileField()
#    password_field = forms.CharField(widget=forms.PasswordInput)
#    textarea = forms.CharField(widget=forms.Textarea)
#    boolean_field = forms.BooleanField()

dicom_web_viewer/misl_viewer/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import RequestContext
#file upload#
from django.forms import *
from misl_viewer.forms import ExampleForm
#model#
from misl_viewer.models import Image
#system cmd#
import os

class testUploadFileForm(Form):
    file = FileField()

def test(request):
    return HttpResponse(u'test')

def index(request):
    '''HOME'''
    msg=''
    FILENAME=''
    name=''
    pngdir = '/root/webapp/django/dicom_viewer/dicom_web_viewer/static/png/'
    MultiFileUpload(request)

    # #-- upload method --#
    # if request.method == 'POST':
    #     form = UploadFileForm(request.POST,request.FILES)
    #     if form.is_valid():
    #         updir = r'/root/webapp/django/dicom_viewer/dicom_web_viewer/static/file/' + form.cleaned_data['name']
    #         destination = open(updir,'wb+')
    #         upfile = request.FILES['file']
    #         for chunk in upfile.chunks():
    #             destination.write(chunk)
    #         destination.close()
    #
    #         # #set#
    #         FILENAME = form.cleaned_data['name']
    #         name , ext = os.path.splitext(FILENAME)
    #
    #         #-- dcm convert --#
    #         cmd2 = "dcm2pnm --write-png "+ filedir + name + ".dcm " + pngdir + name + ".png"
    #         os.system(cmd2)
    #
    # else:
    #     form = UploadFileForm()

    #-- dcm convert --#
    #cmd1 = "dcmdjpeg /root/webapp/django/dicom_viewer/dicom_web_viewer/static/file/" + name + ".dcm /root/webapp/django/dicom_viewer/dicom_web_viewer/static/jpg/" + name + ".dcm"

    return render_to_response('misl_viewer/index.html',  # 使用するテンプレート
                              context_instance=RequestContext(request))  # その他標準のコンテキスト


class UploadFileForm(Form):
	#name = CharField(max_length = 50)
	file = FileField()

def list(request):
    '''画像一覧'''
    images = Image.objects.all()
    print Image.objects.all().order_by('id')
    return render_to_response('misl_viewer/list.html',  # 使用するテンプレート
                              {'images': images},       # テンプレートに渡すデータ
                              context_instance=RequestContext(request))  # その他標準のコンテキスト

def display(request, image_id):
    '''選択画像表示'''
    image_display = get_object_or_404(Image, pk=image_id)
    return render_to_response('misl_viewer/display.html',  # 使用するテンプレート
                              {'images': image_display},       # テンプレートに渡すデータ
                              context_instance=RequestContext(request))  # その他標準のコンテキスト


def Image_del(request,image_id):
    '''画像の削除'''
    image = get_object_or_404(Image, pk=image_id)
    image.delete()
    return redirect('misl_viewer:list')

def Upload(request):
    '''アップロードページ'''
#    return HttpResponse(u'アップロードページ')
    form = ExampleForm()
    return render_to_response('misl_viewer/upload.html',
            {'form':form},
            context_instance=RequestContext(request))

def MultiFileUpload(request):
    '''複数ファイルアップロード'''
    filedir = r'/root/webapp/django/dicom_viewer/dicom_web_viewer/static/file/'
    if request.method == 'POST':
#        print request.POST['select_processing']
 #       print request.POST['set_threshold']
#        print request.FILES
        for f in request.FILES.getlist('upload[]'):
            print f
            updir = filedir + str(f)
            #db save
            i = Image(file_name= str(f))
            #i = Image(file_name= str(f),set_proc= request.POST['select_processing'],set_threshold=request.POST['set_threshold'])
            i.save()
            #
            destination = open(updir,'wb+')
            upfile = request.FILES['upload[]']
            for chunk in upfile.chunks():
                destination.write(chunk)
            destination.close()
        os.system("ssh debian python /root/dicom_image/dicom_addtag.py")
        os.system("ssh debian python /root/dicom_image/dicom_convert.py")
    return redirect('/viewer/list')

dicom_web_viewer/misl_viewer/templates/base copy.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}DICOM Web Viewer{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  {% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
    {{ content }}
    {% endblock %}
  </div>
</body>
</html>

dicom_web_viewer/misl_viewer/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta http-equiv="content-type" charset="UTF-8">
		<title>{% block title %}DICOM Web Viewer{% endblock %}</title>

		<link rel="stylesheet" href="{% static "css/style.css" %}">
		<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
		<script src="{% static 'bootstrap/js/jquery-1.11.2.js' %}"></script>
		<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

		<style>
		#pageHeader #toolbar { display: inline-block; float: right; margin-top: 10px;}
		</style>


		<link rel="stylesheet" href="{% static "ext/jquery/ui/1.10.2/themes/ui-darkness/jquery-ui-1.10.2.min.css" %}">
		<!-- Third party -->
		<script type="text/javascript" src="{% static "ext/jquery/jquery-1.9.1.min.js" %}"></script>
		<script type="text/javascript" src="{% static "ext/jquery/ui/1.10.2/jquery-ui-1.10.2.min.js" %}"></script>
		<script type="text/javascript" src="{% static "ext/flot/jquery.flot.min.js" %}"></script>
		<!-- Local -->
		<script type="text/javascript" src="{% static "src/dwv.js" %}"></script>
		<script type="text/javascript" src="{% static "src/application.js" %}"></script>
		<script type="text/javascript" src="{% static "src/dicom/dicomParser.js" %}"></script>
		<script type="text/javascript" src="{% static "src/dicom/dictionary.js" %}"></script>
		<script type="text/javascript" src="{% static "src/html/gui.js" %}"></script>
		<script type="text/javascript" src="{% static "src/html/gui_ui.js" %}"></script>
		<script type="text/javascript" src="{% static "src/html/html.js" %}"></script>
		<script type="text/javascript" src="{% static "src/html/style.js" %}"></script>
		<script type="text/javascript" src="{% static "src/html/layer.js" %}"></script>
		<script type="text/javascript" src="{% static "src/image/filter.js" %}"></script>
		<script type="text/javascript" src="{% static "src/image/image.js" %}"></script>
		<script type="text/javascript" src="{% static "src/image/view.js" %}"></script>
		<script type="text/javascript" src="{% static "src/image/luts.js" %}"></script>
		<script type="text/javascript" src="{% static "src/image/reader.js" %}"></script>
		<script type="text/javascript" src="{% static "src/math/shapes.js" %}"></script>
		<script type="text/javascript" src="{% static "src/math/bucketQueue.js" %}"></script>
		<script type="text/javascript" src="{% static "src/math/scissors.js" %}"></script>
		<script type="text/javascript" src="{% static "src/utils/string.js" %}"></script>

		<!-- Tools: beware order is important... -->
		<script type="text/javascript" src="{% static "src/tools/toolbox.js" %}"></script>
		<script type="text/javascript" src="{% static "src/tools/windowLevel.js" %}"></script>
		<script type="text/javascript" src="{% static "src/tools/info.js" %}"></script>
		<script type="text/javascript" src="{% static "src/tools/draw.js" %}"></script>
		<script type="text/javascript" src="{% static "src/tools/line.js" %}"></script>
		<script type="text/javascript" src="{% static "src/tools/rectangle.js" %}"></script>
		<script type="text/javascript" src="{% static "src/tools/roi.js" %}"></script>
		<script type="text/javascript" src="{% static "src/tools/circle.js" %}"></script>
		<script type="text/javascript" src="{% static "src/tools/livewire.js" %}"></script>
		<script type="text/javascript" src="{% static "src/tools/zoom.js" %}"></script>
		<script type="text/javascript" src="{% static "src/tools/filter.js" %}"></script>
		<script type="text/javascript" src="{% static "src/tools/undo.js" %}"></script>

		<script type="text/javascript">
function toggle(dialogId)
{
	if( $(dialogId).dialog('isOpen') )
	{
		$(dialogId).dialog('close');
	}
	else
	{
		$(dialogId).dialog('open');
	}
}

// main application
var app = new dwv.App();

// jquery
$(document).ready(function(){
	// initialise buttons
	$("button").button();
	$("#toggleInfoLayer").button({ icons:
		{ primary: "ui-icon-comment" }, text: false });
	// create dialogs
	$("#openData").dialog({ position:
		{my: "left top+100", at: "left top", of: "#pageMain"} });
	$("#toolbox").dialog({ position:
		{my: "left top+255", at: "left top", of: "#pageMain"} });
	$("#history").dialog({ position:
		{my: "left top+410", at: "left top", of: "#pageMain"},
		autoOpen: true });
	$("#tags").dialog({ position:
		{my: "right top", at: "right top", of: "#pageMain"},
		autoOpen: false, width: 500, height: 590 });


	// image dialog
	$("#layerDialog").dialog({ position:
		{my: "left+320 top+100", at: "left top", of: "#pageMain"}});
	// default size
	$("#layerDialog").dialog({ width: "auto", resizable: false });
	// Resizable but keep aspect ratio

	// initialise the application
	app.init();
	// align layers when the window is resized
	window.onresize = app.resize;
	// possible load from URL
	var input = dwv.html.getUriParam("input");
	if( input ) app.loadURL(decodeURIComponent(input));
});
		</script>
		{% block extrahead %}{% endblock %}
	</head>



	<body>
		<div id="pageHeader">
			<!-- Title -->
			<img src="{% static "mislviewer.png" %}">
			<!-- Toolbar -->
			<div id="toolbar">
				<button ><a href="{% url 'misl_viewer:index' %}">Viewer</a></button>
				<button ><a href="{% url 'misl_viewer:list' %}">Gellery</a></button>
				<button onclick="toggle('#openData')">File</button>
				<button onclick="toggle('#toolbox')">Toolbox</button>
				<button ><a href="{% url 'misl_viewer:upload' %}">Upload</a></button>
				<button onclick="toggle('#tags')">Tags</button>
				<button onclick="toggle('#layerDialog')">Image</button>
				<button onclick="app.toggleInfoLayerDisplay()">Info</button>
			</div><!-- /toolbar -->
		</div><!-- /pageHeader -->


		<div class="container">
			{% block content %}
			{{ content }}
			{% endblock %}
		</div>
	</body>
</html>

dicom_web_viewer/misl_viewer/templates/misl_viewer/book_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}書籍の編集{% endblock title %}

{% block content %}
<h3 class="page-header">書籍の編集</h3>
{% if book_id %}
<form action="{% url 'cms:book_mod' book_id=book_id %}" method="post" class="form-horizontal" role="form">
  {% else %}
  <form action="{% url 'cms:book_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
    {% csrf_token %}
    {{ form|bootstrap_horizontal }}
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">送信</button>
      </div>
    </div>
  </form>
  <a href="{% url 'cms:book_list' %}" class="btn btn-default btn-sm">戻る</a>
  {% endblock content %}

dicom_web_viewer/misl_viewer/templates/misl_viewer/display.html
<!DOCTYPE>
<html lang="ja">

<head>
<title>DICOM Web Viewer</title>
<meta http-equiv="content-type" charset="utf-8">
{% load staticfiles %}
<link rel="stylesheet" href="{% static "css/style.css" %}">
<style>
body { font-size: 80%; }
#pageHeader h1 { display: inline-block; margin: 0; }
#pageHeader #toolbar { display: inline-block; float: right; }
#toolbox li:first-child { list-style-type: none; padding-bottom: 10px; margin-left: -20px; }
#pageMain { height: 93%; width: 100%; margin-top: 10px; background-color: #ffffff; }
#infotl { color: #f41c1c; text-shadow: 0 1px 0 #fff; }
#infotr { color: #333; text-shadow: 0 1px 0 #fff; }
</style>
<script>
/*
 alert("Hippocampus of this patient might have atrophied！");
 alert("この患者はアルツハイマー型認知症の可能性があります。海馬の萎縮が検出されました。");
*/
</script>

<link rel="stylesheet" href="{% static "ext/jquery/ui/1.10.2/themes/ui-darkness/jquery-ui-1.10.2.min.css" %}">
<!-- Third party -->
<script type="text/javascript" src="{% static "ext/jquery/jquery-1.9.1.min.js" %}"></script>
<script type="text/javascript" src="{% static "ext/jquery/ui/1.10.2/jquery-ui-1.10.2.min.js" %}"></script>
<script type="text/javascript" src="{% static "ext/flot/jquery.flot.min.js" %}"></script>
<!-- Local -->
<script type="text/javascript" src="{% static "src/dwv.js" %}"></script>
<script type="text/javascript" src="{% static "src/application.js" %}"></script>
<script type="text/javascript" src="{% static "src/dicom/dicomParser.js" %}"></script>
<script type="text/javascript" src="{% static "src/dicom/dictionary.js" %}"></script>
<script type="text/javascript" src="{% static "src/html/gui.js" %}"></script>
<script type="text/javascript" src="{% static "src/html/gui_ui.js" %}"></script>
<script type="text/javascript" src="{% static "src/html/html.js" %}"></script>
<script type="text/javascript" src="{% static "src/html/style.js" %}"></script>
<script type="text/javascript" src="{% static "src/html/layer.js" %}"></script>
<script type="text/javascript" src="{% static "src/image/filter.js" %}"></script>
<script type="text/javascript" src="{% static "src/image/image.js" %}"></script>
<script type="text/javascript" src="{% static "src/image/view.js" %}"></script>
<script type="text/javascript" src="{% static "src/image/luts.js" %}"></script>
<script type="text/javascript" src="{% static "src/image/reader.js" %}"></script>
<script type="text/javascript" src="{% static "src/math/shapes.js" %}"></script>
<script type="text/javascript" src="{% static "src/math/bucketQueue.js" %}"></script>
<script type="text/javascript" src="{% static "src/math/scissors.js" %}"></script>
<script type="text/javascript" src="{% static "src/utils/string.js" %}"></script>

<!-- Tools: beware order is important... -->
<script type="text/javascript" src="{% static "src/tools/toolbox.js" %}"></script>
<script type="text/javascript" src="{% static "src/tools/windowLevel.js" %}"></script>
<script type="text/javascript" src="{% static "src/tools/info.js" %}"></script>
<script type="text/javascript" src="{% static "src/tools/draw.js" %}"></script>
<script type="text/javascript" src="{% static "src/tools/line.js" %}"></script>
<script type="text/javascript" src="{% static "src/tools/rectangle.js" %}"></script>
<script type="text/javascript" src="{% static "src/tools/roi.js" %}"></script>
<script type="text/javascript" src="{% static "src/tools/circle.js" %}"></script>
<script type="text/javascript" src="{% static "src/tools/livewire.js" %}"></script>
<script type="text/javascript" src="{% static "src/tools/zoom.js" %}"></script>
<script type="text/javascript" src="{% static "src/tools/filter.js" %}"></script>
<script type="text/javascript" src="{% static "src/tools/undo.js" %}"></script>

<script type="text/javascript">

function toggle(dialogId)
{
	if( $(dialogId).dialog('isOpen') )
	{
		$(dialogId).dialog('close');
	}
	else
	{
		$(dialogId).dialog('open');
	}
}

// main application
var app = new dwv.App();

// jquery
$(document).ready(function(){
    // initialise buttons
    $("button").button();
    $("#toggleInfoLayer").button({ icons:
        { primary: "ui-icon-comment" }, text: false });
    // create dialogs
    $("#openData").dialog({ position:
		{my: "left top+100", at: "left top", of: "#pageMain"},
				autoOpen:false });
    $("#toolbox").dialog({ position:
		{my: "left top+255", at: "left top", of: "#pageMain"},
				autoOpen:false });
    $("#history").dialog({ position:
        {my: "left top+410", at: "left top", of: "#pageMain"},
        autoOpen: false });
    $("#tags").dialog({ position:
        {my: "right top", at: "right top", of: "#pageMain"},
        autoOpen: true, width: 600, height: 590 });

    // image dialog
    $("#layerDialog").dialog({ position:
        {my: "left top+100", at: "left top", of: "#pageMain"}});
    // default size
    $("#layerDialog").dialog({ width: "auto", resizable: false });
    // Resizable but keep aspect ratio
    // TODO it seems to add a border that bothers getting the cursor position...
    //$("#layerContainer").resizable({ aspectRatio: true });

    // initialise the application
    app.init();
    // align layers when the window is resized
    window.onresize = app.resize;
    // possible load from URL
    // var input = dwv.html.getUriParam("http://172.22.54.166:8000{% static "mislviewer.png" %}");
    // if( input ) app.loadURL(decodeURIComponent(input));
    app.loadURL("http://172.22.54.166:8000/static/file/{{ images.file_name }}");
});
</script>
</head>



<body>

	<div id="pageHeader">
		<!-- Title -->
		<img src="{% static "mislviewer.png" %}">
		<!-- Toolbar -->
		<div id="toolbar">
			<button ><a href="{% url 'misl_viewer:index' %}">Viewer</a></button>
			<button ><a href="{% url 'misl_viewer:list' %}">Gellery</a></button>
			<button onclick="toggle('#openData')">File</button>
			<button onclick="toggle('#toolbox')">Toolbox</button>
			<button ><a href="{% url 'misl_viewer:upload' %}">Upload</a></button>
			<button onclick="toggle('#tags')">Tags</button>
			<button onclick="toggle('#layerDialog')">Image</button>
			<button onclick="app.toggleInfoLayerDisplay()">Info</button>
		</div><!-- /toolbar -->
	</div><!-- /pageHeader -->

<div id="pageMain">

	<!-- Open file -->
	<div id="openData" title="File">
		<form><p>
			Path: <input type="file" id="imagefiles" multiple />
			Path: <input type="url" id="imageurl" multiple />
		</p></form>
	</div>

	<!-- Toolbox -->
	<div id="toolbox" title="Toolbox">
		<ul id="toolList"></ul>
	</div>

	<!-- History -->
	<div id="history" title="upload">
		<!-- Upload -->
		<form enctype="multipart/form-data" action='/viewer/' method='POST'>{% csrf_token %}
			<input type='file' name="upload[]" multiple="multiple">
			<input type='submit' value=" UPLOAD ">
		</form>
	</div>

	<!-- Tags -->
	<div id="tags" title="Tags" style="display:none;"></div>

	<!-- Layer Container -->
	<div id="layerDialog" title="Image">
		<div id="layerContainer">
			<canvas id="imageLayer">Only for HTML5 compatible browsers...</canvas>
			<canvas id="drawLayer">Only for HTML5 compatible browsers...</canvas>
			<canvas id="tempLayer">Only for HTML5 compatible browsers...</canvas>
			<div id="infoLayer">
				<div id="infotl"></div>
				<div id="infotr"></div>
				<div id="infobl"></div>
				<div id="infobr"><div id="plot"></div></div>
			</div><!-- /infoLayer -->
		</div><!-- /layerContainer -->
	</div><!-- /layerDialog -->

</div><!-- /pageMain -->

</body>
</html>

dicom_web_viewer/misl_viewer/templates/misl_viewer/list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extrahead %}
<style type="text/css">
.tab{overflow:hidden;}
.tab li{background:#ccc; padding:5px 25px; float:left; margin-right:1px;}
.tab li.select{background:#eee;}
/*.content li{background:#eee; padding:20px;}*/
.hide_content {display:none;}
li {padding-left:0px;list-style:none;}
</style>

<!-- Third party -->
<script type="text/javascript" src="{% static "ext/jquery/jquery-1.9.1.min.js" %}"></script>
<script type="text/javascript" src="{% static "ext/jquery/ui/1.10.2/jquery-ui-1.10.2.min.js" %}"></script>
<script type="text/javascript">
$(function() {
	//クリックしたときのファンクションをまとめて指定
	$('.tab li').click(function() {

		//.index()を使いクリックされたタブが何番目かを調べ、
		//indexという変数に代入します。
		var index = $('.tab li').index(this);

		//コンテンツを一度すべて非表示にし、
		$('.content li').css('display','none');

		//クリックされたタブと同じ順番のコンテンツを表示します。
		$('.content li').eq(index).css('display','block');

		//一度タブについているクラスselectを消し、
		$('.tab li').removeClass('select');

		//クリックされたタブのみにクラスselectをつけます。
		$(this).addClass('select')
	});
});
</script>


{% endblock %}
{% block content %}

<h1>Gallery</h1>
<hr \>


<ul class="tab">
	<li class="select">患者A</li>
	<li>患者B</li>
	<li>患者C</li>
	<li>患者D</li>
</ul>

<ul class="content">
	<li>
		<table class="table table-hover table-bordered">
			<thead>
				<th>ID</th>
				<th>Date</th>
				<th>Img</th>
				<th>Name</th>
				<th>Add tag</th>
				<th>Threshold</th>
				<th>Action</th>
			</thead>

			<tbody>
				<!-- list -->
				{% for image in images %}
				{% if image.id == 47 %}
				<tr>
					<td class="danger">{{ image.id }}</td>
					<td class="danger">{{ image.upload_date }}</td>
					<td class="danger"><img src="{{ STATIC_URL }}file/png/{{ image.file_name }}.png" width="80" height="60" ></td>

					<td class="danger">{{ image.file_name }}</td>
					<td class="danger">{{ image.set_tag }}</td>
					<td class="danger">{{ image.set_threshold }}</td>
					<td class="danger">
						<a href="{% url 'misl_viewer:image_del' image_id=image.id %}" class="btn btn-default btn-sm">削除</a>
						<a href="{% url 'misl_viewer:display' image_id=image.id %}" class="btn btn-default btn-sm">表示</a>
						<a href="#" class="btn btn-default btn-sm">修正</a>
					</td>
				</tr>
				{% else %}
				<tr>
					<td>{{ image.id }}</td>
					<td>{{ image.upload_date }}</td>
					<td><img src="{{ STATIC_URL }}file/png/{{ image.file_name }}.png" width="80" height="60" ></td>

					<td>{{ image.file_name }}</td>
					<td>{{ image.set_tag }}</td>
					<td>{{ image.set_threshold }}</td>
					<td>
						<a href="{% url 'misl_viewer:image_del' image_id=image.id %}" class="btn btn-default btn-sm">削除</a>
						<a href="{% url 'misl_viewer:display' image_id=image.id %}" class="btn btn-default btn-sm">表示</a>
						<a href="#" class="btn btn-default btn-sm">修正</a>
					</td>
				</tr>
				{% endif %}
				{% endfor %}
			</tbody>
		</table>
	</li>

	<li class="hide_content">test1</li>
	<li class="hide_content">test2</li>
	<li class="hide_content">test3</li>
</ul>

{% endblock content %}